[package]
name = "ron"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.24"
strum = "0.24"
strum_macros = "0.24"
duplicate = "0.4.1"

[dev-dependencies]
criterion = {version = "0.4.0", features = ["html_reports"] }
# Serde is used for comparison in benchmarks
serde = "1.0.152"
serde_json = "1.0.91"

[[bench]]
name = "reader_benchmark"
# Disable default harness because Criterion creates its own
harness = false

[[bench]]
name = "reader_struct_benchmark"
# Disable default harness because Criterion creates its own
harness = false

[[bench]]
name = "writer_benchmark"
# Disable default harness because Criterion creates its own
harness = false

[[bench]]
name = "writer_struct_benchmark"
# Disable default harness because Criterion creates its own
harness = false
