name: Build

on: [push, pull_request]

permissions:
  contents: read # to fetch code (actions/checkout)

env:
  # Enable colored terminal output, see https://doc.rust-lang.org/cargo/reference/config.html#termcolor
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Build (${{ matrix.os }})

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-make
        uses: davidB/rust-cargo-make@10579dcff82285736fad5291533b52d3c93d6b3b
        with:
          version: '0.37.2'

      - name: Build
        run: cargo make
